c_compiler:
- gcc
c_compiler_version:
- '12'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cuda_compiler:
- None
cuda_compiler_version:
- None
docker_image:
- e8035669/linux-anvil-armv7l
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
python:
- 3.11.* *_cpython
- 3.10.* *_cpython
- 3.9.* *_cpython
- 3.8.* *_cpython
target_platform:
- linux-armv7l
zip_keys:
- - c_compiler_version
  - cuda_compiler
  - cuda_compiler_version
  - cdt_name
  - docker_image
